services:
  - type: web
    name: java-springboot-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
